#!/bin/bash

cd /Users/sandeshgoel/Google\ Drive/FINANCE/SCRAPING
source ~/.bash_profile

echo $(date) 
#echo $PATH 

echo $(date) > LOGS/log.weekly_run 2>&1

python3 analyze/send_latest_report.py >> LOGS/log.weekly_run 2>&1
python3 scrape/cams.py -v >> LOGS/log.weekly_run 2>&1